DROP TABLE IF EXISTS users, items;

CREATE table IF NOT EXISTS users(
    user_id int generated by default as identity primary key,
    email varchar NOT NULL,
    name varchar NOT NULL
);
CREATE unique index if not exists user_email_uindex ON users (email);

CREATE table IF NOT EXISTS items(
    item_id int generated by default as identity primary key,
    name varchar(50) NOT NULL,
    description varchar NOT NULL,
    is_available boolean,
    owner_id int REFERENCES users (user_id) ON DELETE CASCADE
);